name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Application
        run: |
          ssh user@154.159.231.250 << 'EOF'
            cd ~/fastapi-book-project
            git pull origin main
            docker-compose down
            docker-compose up --build -d
          EOF
